# Generated by Django 4.1.5 on 2023-01-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='paid',
            field=models.IntegerField(),
        ),
    ]
