# Generated by Django 4.1.5 on 2023-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
