# Generated by Django 4.1.5 on 2023-01-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_accounts_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_link', models.URLField()),
                ('encode_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire', models.BooleanField(default=False)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
            options={
                'db_table': 'links',
            },
        ),
    ]
